### ISSUE TITLE
Can you provide these csv files?

### ISSUE THREAD

**Issue by Before-Rain** [QDaiing/FedMEMA#1]
Thanks for your excellent work!
I am trying to reproduce your work, can you provide these csv files please?
![image](https://github.com/QDaiing/FedMEMA/assets/65607895/8de93920-6861-4f91-a7a1-a98a5cd2df6c)

**Comment by chunyuxiaodao** [comment]
你好，请问你之后在哪找到了这些文件？可以指导一下吗
Hello, where did you find these files? Can you give me some guidance
@xhjy2020

**Comment by Before-Rain** [comment]
You can leave an email and I'll forward the file to you.

**Comment by chunyuxiaodao** [comment]
Thank you for your reply. My email is ***@***.***




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "QDaiing/FedMEMA"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年5月15日(星期三) 下午5:25
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [QDaiing/FedMEMA] Can you provide these csv files? (Issue #1)





 
You can leave an email and I'll forward the file to you.

**Comment by Before-Rain** [comment]
[split_4c_1g_1v_1t_dup (1).zip](https://github.com/QDaiing/FedMEMA/files/15319374/split_4c_1g_1v_1t_dup.1.zip)

**Comment by Before-Rain** [comment]
![image](https://github.com/QDaiing/FedMEMA/assets/65607895/f89ddde8-600f-4fb0-b4cc-502d2df0ceed)
邮件是被屏蔽了吗。。我刚传了一份上来，你看看能不能下载。作者说：“It should be noted that the contents of "split_4c_1g_1v_1t/glb.csv" and "split_4c_1g_1v_1t_dup/glb.csv" are the same. So we only provided one.”

**Comment by chunyuxiaodao** [comment]
Thank you for your guidance and wish you a happy life.



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "QDaiing/FedMEMA"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年5月15日(星期三) 下午5:31
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [QDaiing/FedMEMA] Can you provide these csv files? (Issue #1)





 
split_4c_1g_1v_1t_dup (1).zip

**Comment by azxzxx** [comment]
> ![image](https://github.com/QDaiing/FedMEMA/assets/65607895/f89ddde8-600f-4fb0-b4cc-502d2df0ceed) 邮件是被屏蔽了吗。。我刚传了一份上来，你看看能不能下载。作者说：“It should be noted that the contents of "split_4c_1g_1v_1t/glb.csv" and "split_4c_1g_1v_1t_dup/glb.csv" are the same. So we only provided one.”

同学 你这打开是brats18  它论文是brats20
